#!/bin/sh

cat <<EOF
{
  "GITHUB_TOKEN": "$GITHUB_TOKEN",
  "ECHO_SERVICE_DOCKERHUB_IMAGE": "$ECHO_SERVICE_DOCKERHUB_IMAGE",
  "DOCKERHUB_USERNAME": "$DOCKERHUB_USERNAME",
  "DOCKERHUB_TOKEN": "$DOCKERHUB_TOKEN"
}
EOF
